
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fogonsisabors_prod_app
    restart: always
    volumes:
      - public_assets:/var/www/html/public
      - storage_data:/var/www/html/storage
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-fogonsisabors}
      - DB_USERNAME=${DB_USERNAME:-fogonsisabors}
      - DB_PASSWORD=${DB_PASSWORD:-fogons_securizada}
      # Correu electrònic via injectat 
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - laravel_prod
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: fogonsisabors_prod_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - public_assets:/var/www/html/public
      - storage_data:/var/www/html/storage
    networks:
      - laravel_prod
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: fogonsisabors_prod_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-fogonsisabors}
      MYSQL_USER: ${DB_USERNAME:-fogonsisabors}
      MYSQL_PASSWORD: ${DB_PASSWORD:-fogons_securizada}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-fogons_securizada}
    volumes:
      - dbdata_prod:/var/lib/mysql
    networks:
      - laravel_prod

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fogonsisabors_prod_phpmyadmin
    # Inactiu per defecte, només s'aixecarà amb: docker compose --profile debug up
    profiles: ["debug"]
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME:-fogonsisabors}
      - PMA_PASSWORD=${DB_PASSWORD:-fogons_securizada}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel_prod

networks:
  laravel_prod:
    driver: bridge

volumes:
  dbdata_prod:
  public_assets:
    name: fogons_public_assets
  storage_data:
    name: fogons_storage_data
